version: "3.2"
services:
  web:
    image: nginx:latest
    ports:
      - "4000:80"
    volumes:
      - ./server:/server
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: php:fpm
    volumes:
      - ./server:/server
    networks:
      - code-network
  app:
    build:
      context: ./app/
    command: yarn dev
    volumes:
      - ./app/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
networks:
  code-network:
    driver: bridge